[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP Server to query NYC rental data with StreetEasyAPI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.1",
    "mcp[cli]>=1.10.1",
    "requests==2.32.4",
]
